#include "config.h"
#include <stdio.h>
#include <assert.h>
#include <common/wireaddr.h>
#include <common/bigsize.h>
#include <common/channel_id.h>
#include <common/setup.h>
#include <common/utils.h>

static bool print_enable = true;
#define SUPERVERBOSE(...) do { if (print_enable) printf(__VA_ARGS__); } while(0)

#include <plugins/renepay/flow.h>
#include "../flow.c"

/* AUTOGENERATED MOCKS START */
/* Generated stub for fromwire_bigsize */
bigsize_t fromwire_bigsize(const u8 **cursor UNNEEDED, size_t *max UNNEEDED)
{ fprintf(stderr, "fromwire_bigsize called!\n"); abort(); }
/* Generated stub for fromwire_channel_id */
bool fromwire_channel_id(const u8 **cursor UNNEEDED, size_t *max UNNEEDED,
			 struct channel_id *channel_id UNNEEDED)
{ fprintf(stderr, "fromwire_channel_id called!\n"); abort(); }
/* Generated stub for fromwire_wireaddr */
bool fromwire_wireaddr(const u8 **cursor UNNEEDED, size_t *max UNNEEDED, struct wireaddr *addr UNNEEDED)
{ fprintf(stderr, "fromwire_wireaddr called!\n"); abort(); }
/* Generated stub for towire_bigsize */
void towire_bigsize(u8 **pptr UNNEEDED, const bigsize_t val UNNEEDED)
{ fprintf(stderr, "towire_bigsize called!\n"); abort(); }
/* Generated stub for towire_channel_id */
void towire_channel_id(u8 **pptr UNNEEDED, const struct channel_id *channel_id UNNEEDED)
{ fprintf(stderr, "towire_channel_id called!\n"); abort(); }
/* Generated stub for towire_wireaddr */
void towire_wireaddr(u8 **pptr UNNEEDED, const struct wireaddr *addr UNNEEDED)
{ fprintf(stderr, "towire_wireaddr called!\n"); abort(); }
/* AUTOGENERATED MOCKS END */

static void test_edge_probability(void)
{
	const double eps = 1e-8;
	
	struct amount_msat min = AMOUNT_MSAT(10); // known min
	struct amount_msat max = AMOUNT_MSAT(19); // known max
	
	struct amount_msat X = AMOUNT_MSAT(0); // in flight
	struct amount_msat f;
	
	for(int i=0;i<=min.millisatoshis;++i)
	{
		f.millisatoshis = i;
		// prob = 1
		assert(fabs(edge_probability(min,max,X,f)-1.0)< eps);
	}
	for(int i=max.millisatoshis+1;i<=100;++i)
	{
		f.millisatoshis = i;
		// prob = 0
		assert(fabs(edge_probability(min,max,X,f))< eps);
	}
	f.millisatoshis=11;
	assert(fabs(edge_probability(min,max,X,f)-0.9)< eps);
	
	f.millisatoshis=12;
	assert(fabs(edge_probability(min,max,X,f)-0.8)< eps);
	
	f.millisatoshis=13;
	assert(fabs(edge_probability(min,max,X,f)-0.7)< eps);
	
	f.millisatoshis=14;
	assert(fabs(edge_probability(min,max,X,f)-0.6)< eps);
	
	f.millisatoshis=15;
	assert(fabs(edge_probability(min,max,X,f)-0.5)< eps);
	
	f.millisatoshis=16;
	assert(fabs(edge_probability(min,max,X,f)-0.4)< eps);
	
	f.millisatoshis=17;
	assert(fabs(edge_probability(min,max,X,f)-0.3)< eps);
	
	f.millisatoshis=18;
	assert(fabs(edge_probability(min,max,X,f)-0.2)< eps);
	
	f.millisatoshis=19;
	assert(fabs(edge_probability(min,max,X,f)-0.1)< eps);
	
	X = AMOUNT_MSAT(5);
	
	// X<A, f<A-X
	for(int i=0;i<=5;++i)
	{
		f.millisatoshis = i;
		// prob = 1
		assert(fabs(edge_probability(min,max,X,f)-1.0)< eps);
	}
	// X<A, f>=B-X
	for(int i=15;i<100;++i)
	{
		f.millisatoshis = i;
		// prob = 0
		assert(fabs(edge_probability(min,max,X,f))< eps);
	}
	// X<A, A-X<=f<=B-X
	f.millisatoshis=6;
	assert(fabs(edge_probability(min,max,X,f)-0.9)< eps);
	f.millisatoshis=7;
	assert(fabs(edge_probability(min,max,X,f)-0.8)< eps);
	f.millisatoshis=8;
	assert(fabs(edge_probability(min,max,X,f)-0.7)< eps);
	f.millisatoshis=9;
	assert(fabs(edge_probability(min,max,X,f)-0.6)< eps);
	f.millisatoshis=10;
	assert(fabs(edge_probability(min,max,X,f)-0.5)< eps);
	f.millisatoshis=11;
	assert(fabs(edge_probability(min,max,X,f)-0.4)< eps);
	f.millisatoshis=12;
	assert(fabs(edge_probability(min,max,X,f)-0.3)< eps);
	f.millisatoshis=13;
	assert(fabs(edge_probability(min,max,X,f)-0.2)< eps);
	f.millisatoshis=14;
	assert(fabs(edge_probability(min,max,X,f)-0.1)< eps);
	
	X = AMOUNT_MSAT(15);
	
	// f>=B-X
	for(int i=5;i<100;++i)
	{
		f.millisatoshis = i;
		assert(fabs(edge_probability(min,max,X,f))< eps);
	}
	
	// X>=A, 0<=f<=B-X
	f.millisatoshis=0;
	assert(fabs(edge_probability(min,max,X,f)-1.0)< eps);
	f.millisatoshis=1;
	assert(fabs(edge_probability(min,max,X,f)-0.8)< eps);
	f.millisatoshis=2;
	assert(fabs(edge_probability(min,max,X,f)-0.6)< eps);
	f.millisatoshis=3;
	assert(fabs(edge_probability(min,max,X,f)-0.4)< eps);
	f.millisatoshis=4;
	assert(fabs(edge_probability(min,max,X,f)-0.2)< eps);
	f.millisatoshis=5;
	assert(fabs(edge_probability(min,max,X,f)-0.0)< eps);
}

int main(int argc, char *argv[])
{
	common_setup(argv[0]);
	
	test_edge_probability();
	
	common_shutdown();
}

