/* This file was generated by generate-wire.py */
/* Do not modify this file! Modify the .csv file it was generated from. */
/* Template located at tools/gen/print_header_template */
#ifndef LIGHTNING_WIRE_CHANNEL_TYPE_PRINTGEN_H
#define LIGHTNING_WIRE_CHANNEL_TYPE_PRINTGEN_H
#include <ccan/tal/tal.h>
#include <devtools/print_wire.h>

void printchannel_type_wire_message(const u8 *msg);

void printchannel_type_wire_tlv_message(const char *tlv_name, const u8 *msg);


void printwire_channel_type(const char *fieldname, const u8 **cursor, size_t *plen);
#endif /* LIGHTNING_WIRE_CHANNEL_TYPE_PRINTGEN_H */
// SHA256STAMP:bb90bdf85bc5e833dfca202bb6502512dcf7c7786c919a798e130884e373d536
