/* This file was generated by generate-wire.py */
/* Do not modify this file! Modify the _csv file it was generated from. */
/* Original template can be found at tools/gen/header_template */

#ifndef LIGHTNING_WIRE_CHANNEL_TYPE_WIREGEN_H
#define LIGHTNING_WIRE_CHANNEL_TYPE_WIREGEN_H
#include <ccan/tal/tal.h>
#include <wire/tlvstream.h>
#include <wire/wire.h>


struct channel_type {
        u8 *features;
};

/* SUBTYPE: CHANNEL_TYPE */
/*  Why not let our generator generate this too? */
void towire_channel_type(u8 **p, const struct channel_type *channel_type);
struct channel_type *fromwire_channel_type(const tal_t *ctx, const u8 **cursor, size_t *plen);


#endif /* LIGHTNING_WIRE_CHANNEL_TYPE_WIREGEN_H */
// SHA256STAMP:bb90bdf85bc5e833dfca202bb6502512dcf7c7786c919a798e130884e373d536
